# Generated by Django 3.0.5 on 2021-02-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название рецепта')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('units', models.CharField(max_length=40, verbose_name='Название рецепта')),
            ],
        ),
    ]
