# Generated by Django 3.0.5 on 2021-02-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('шт', 'шт'), ('гр', 'гр')], max_length=40),
        ),
    ]
