# Generated by Django 3.0.5 on 2021-02-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210222_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('шт', 'шт'), ('гр', 'гр')], max_length=40, verbose_name='единицы измерения'),
        ),
    ]
