# Generated by Django 3.0.5 on 2021-02-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
