# Generated by Django 3.0.5 on 2021-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210222_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=40, verbose_name='единицы измерения'),
        ),
    ]
