# Generated by Django 3.0.5 on 2021-02-26 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='subscribers',
            field=models.ManyToManyField(blank=True, default=None, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
