# Generated by Django 3.0.5 on 2021-02-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210222_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='количество'),
        ),
    ]
