version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: serg733/foodgram:lastest
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
    volumes:
      - /etc/letsencrypt/live/foodgram.students.nomoredomains.icu/:/etc/letsencrypt/live/foodgram.students.nomoredomains.icu/
      - ./build:/code/build
      - ./static:/code/static
      - ./media:/code/media

  nginx:
    image: nginx:1.19.7
    #    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./static:/code/static
      - ./media:/code/media
      - ./build:/code/build
    depends_on:
      - web

